/* Generated by Pyrex 0.9.8.6 on Tue Aug 30 01:03:29 2011 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "numpy/arrayobject.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from PI.align */


/* Declarations from implementation of PI.align */

static PyTypeObject *__pyx_ptype_2PI_5align_ndarray = 0;

static char __pyx_k1[] = "numpy";
static char __pyx_k2[] = "zeros";
static char __pyx_k3[] = "i";
static char __pyx_k4[] = "append";
static char __pyx_k5[] = "range";

static PyObject *__pyx_n_append;
static PyObject *__pyx_n_i;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_range;
static PyObject *__pyx_n_zeros;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_append, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_i, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_numpy, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_range, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_zeros, 1, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0, 0}
};



/* Implementation of PI.align */

static PyObject *__pyx_f_2PI_5align_NeedlemanWunsch(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2PI_5align_NeedlemanWunsch(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_seq1 = 0;
  PyObject *__pyx_v_seq2 = 0;
  PyObject *__pyx_v_S = 0;
  int __pyx_v_g;
  int __pyx_v_e;
  int __pyx_v_M;
  int __pyx_v_N;
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_v_t_max;
  int __pyx_v_i_max;
  int __pyx_v_j_max;
  int __pyx_v_dir;
  int __pyx_v_v1;
  int __pyx_v_v2;
  int __pyx_v_v3;
  int __pyx_v_m;
  int __pyx_v_new_len;
  int __pyx_v_data;
  int __pyx_v_ni;
  int __pyx_v_nj;
  PyArrayObject *__pyx_v_a;
  int __pyx_v_nrows;
  int __pyx_v_ncols;
  int *__pyx_v_matrix;
  PyObject *__pyx_v_edits1;
  PyObject *__pyx_v_edits2;
  PyObject *__pyx_v_table;
  PyObject *__pyx_v_new_seq1;
  PyObject *__pyx_v_new_seq2;
  int __pyx_v_s1;
  int __pyx_v_s2;
  int __pyx_v_gaps;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  long __pyx_7;
  static char *__pyx_argnames[] = {"seq1","seq2","S","g","e",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOii", __pyx_argnames, &__pyx_v_seq1, &__pyx_v_seq2, &__pyx_v_S, &__pyx_v_g, &__pyx_v_e)) return 0;
  Py_INCREF(__pyx_v_seq1);
  Py_INCREF(__pyx_v_seq2);
  Py_INCREF(__pyx_v_S);
  __pyx_v_a = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_edits1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_edits2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_table = Py_None; Py_INCREF(Py_None);
  __pyx_v_new_seq1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_new_seq2 = Py_None; Py_INCREF(Py_None);

  /* "/private/tmp/PI/PI/align.pyx":26 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  Py_DECREF(__pyx_v_edits1);
  __pyx_v_edits1 = __pyx_1;
  __pyx_1 = 0;

  /* "/private/tmp/PI/PI/align.pyx":27 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  Py_DECREF(__pyx_v_edits2);
  __pyx_v_edits2 = __pyx_1;
  __pyx_1 = 0;

  /* "/private/tmp/PI/PI/align.pyx":29 */
  __pyx_2 = PyObject_Length(__pyx_v_seq1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_v_M = (__pyx_2 + 1);

  /* "/private/tmp/PI/PI/align.pyx":30 */
  __pyx_2 = PyObject_Length(__pyx_v_seq2); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_v_N = (__pyx_2 + 1);

  /* "/private/tmp/PI/PI/align.pyx":32 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_M); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_N); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_5 = PyList_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_1 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_5);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_i);
  __pyx_5 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_table);
  __pyx_v_table = __pyx_4;
  __pyx_4 = 0;

  /* "/private/tmp/PI/PI/align.pyx":34 */
  if (!__Pyx_TypeTest(__pyx_v_table, __pyx_ptype_2PI_5align_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
  Py_INCREF(__pyx_v_table);
  Py_DECREF(((PyObject *)__pyx_v_a));
  __pyx_v_a = ((PyArrayObject *)__pyx_v_table);

  /* "/private/tmp/PI/PI/align.pyx":36 */
  __pyx_v_nrows = (__pyx_v_a->dimensions[0]);

  /* "/private/tmp/PI/PI/align.pyx":37 */
  __pyx_v_ncols = (__pyx_v_a->dimensions[1]);

  /* "/private/tmp/PI/PI/align.pyx":39 */
  __pyx_v_matrix = ((int *)__pyx_v_a->data);

  /* "/private/tmp/PI/PI/align.pyx":42 */
  for (__pyx_v_i = 1; __pyx_v_i < __pyx_v_M; ++__pyx_v_i) {
    for (__pyx_v_j = 1; __pyx_v_j < __pyx_v_N; ++__pyx_v_j) {
      __pyx_5 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_seq1, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_1 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_seq2, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      if (PyObject_Cmp(__pyx_3, __pyx_4, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
      __pyx_6 = __pyx_6 == 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      if (__pyx_6) {
        (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = 1;
        goto __pyx_L6;
      }
      /*else*/ {
        (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = 0;
      }
      __pyx_L6:;
    }
  }

  /* "/private/tmp/PI/PI/align.pyx":50 */
  __pyx_v_i_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":51 */
  __pyx_v_j_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":52 */
  __pyx_v_t_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":54 */
  for (__pyx_v_i = 1; __pyx_v_i < __pyx_v_M; ++__pyx_v_i) {
    for (__pyx_v_j = 1; __pyx_v_j < __pyx_v_N; ++__pyx_v_j) {

      /* "/private/tmp/PI/PI/align.pyx":57 */
      __pyx_v_dir = 0;

      /* "/private/tmp/PI/PI/align.pyx":59 */
      __pyx_v_v1 = (__pyx_v_matrix[(((__pyx_v_i - 1) * __pyx_v_ncols) + (__pyx_v_j - 1))]);

      /* "/private/tmp/PI/PI/align.pyx":60 */
      __pyx_v_v2 = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + (__pyx_v_j - 1))]);

      /* "/private/tmp/PI/PI/align.pyx":61 */
      __pyx_v_v3 = (__pyx_v_matrix[(((__pyx_v_i - 1) * __pyx_v_ncols) + __pyx_v_j)]);

      /* "/private/tmp/PI/PI/align.pyx":63 */
      __pyx_6 = (__pyx_v_v1 > 255);
      if (__pyx_6) {
        __pyx_v_v1 = (__pyx_v_v1 >> 8);
        goto __pyx_L11;
      }
      __pyx_L11:;

      /* "/private/tmp/PI/PI/align.pyx":65 */
      __pyx_6 = (__pyx_v_v2 > 255);
      if (__pyx_6) {
        __pyx_v_v2 = (__pyx_v_v2 >> 8);
        goto __pyx_L12;
      }
      __pyx_L12:;

      /* "/private/tmp/PI/PI/align.pyx":67 */
      __pyx_6 = (__pyx_v_v3 > 255);
      if (__pyx_6) {
        __pyx_v_v3 = (__pyx_v_v3 >> 8);
        goto __pyx_L13;
      }
      __pyx_L13:;

      /* "/private/tmp/PI/PI/align.pyx":70 */
      __pyx_v_v1 = (__pyx_v_v1 + (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]));

      /* "/private/tmp/PI/PI/align.pyx":71 */
      __pyx_v_v2 = (__pyx_v_v2 - __pyx_v_e);

      /* "/private/tmp/PI/PI/align.pyx":72 */
      __pyx_v_v3 = (__pyx_v_v3 - __pyx_v_e);

      /* "/private/tmp/PI/PI/align.pyx":74 */
      __pyx_6 = (__pyx_v_v1 > 0);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v1;
        goto __pyx_L14;
      }
      /*else*/ {
        __pyx_v_m = 0;
      }
      __pyx_L14:;

      /* "/private/tmp/PI/PI/align.pyx":79 */
      __pyx_6 = (__pyx_v_v2 > __pyx_v_m);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v2;
        goto __pyx_L15;
      }
      __pyx_L15:;

      /* "/private/tmp/PI/PI/align.pyx":82 */
      __pyx_6 = (__pyx_v_v3 > __pyx_v_m);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v3;
        goto __pyx_L16;
      }
      __pyx_L16:;

      /* "/private/tmp/PI/PI/align.pyx":85 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v1);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 0));
        goto __pyx_L17;
      }
      __pyx_L17:;

      /* "/private/tmp/PI/PI/align.pyx":88 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v2);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 1));
        goto __pyx_L18;
      }
      __pyx_L18:;

      /* "/private/tmp/PI/PI/align.pyx":91 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v3);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 2));
        goto __pyx_L19;
      }
      __pyx_L19:;

      /* "/private/tmp/PI/PI/align.pyx":94 */
      __pyx_6 = (__pyx_v_m >= __pyx_v_t_max);
      if (__pyx_6) {

        /* "/private/tmp/PI/PI/align.pyx":95 */
        __pyx_v_t_max = __pyx_v_m;

        /* "/private/tmp/PI/PI/align.pyx":96 */
        __pyx_v_i_max = __pyx_v_i;

        /* "/private/tmp/PI/PI/align.pyx":97 */
        __pyx_v_j_max = __pyx_v_j;
        goto __pyx_L20;
      }
      __pyx_L20:;

      /* "/private/tmp/PI/PI/align.pyx":99 */
      __pyx_v_m = (__pyx_v_m << 8);

      /* "/private/tmp/PI/PI/align.pyx":100 */
      __pyx_v_m = (__pyx_v_m | __pyx_v_dir);

      /* "/private/tmp/PI/PI/align.pyx":102 */
      (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = __pyx_v_m;
    }
  }

  /* "/private/tmp/PI/PI/align.pyx":105 */
  __pyx_v_i = __pyx_v_i_max;

  /* "/private/tmp/PI/PI/align.pyx":106 */
  __pyx_v_j = __pyx_v_j_max;

  /* "/private/tmp/PI/PI/align.pyx":108 */
  __pyx_v_new_len = 0;

  /* "/private/tmp/PI/PI/align.pyx":110 */
  while (1) {
    __pyx_6 = __pyx_v_i;
    if (__pyx_6) {
      __pyx_6 = __pyx_v_j;
    }
    if (!__pyx_6) break;

    /* "/private/tmp/PI/PI/align.pyx":111 */
    __pyx_v_data = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]);

    /* "/private/tmp/PI/PI/align.pyx":113 */
    __pyx_7 = (__pyx_v_data & (1 << 2));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":114 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":115 */
      __pyx_v_nj = __pyx_v_j;
      goto __pyx_L23;
    }
    __pyx_L23:;

    /* "/private/tmp/PI/PI/align.pyx":117 */
    __pyx_7 = (__pyx_v_data & (1 << 1));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":118 */
      __pyx_v_ni = __pyx_v_i;

      /* "/private/tmp/PI/PI/align.pyx":119 */
      __pyx_v_nj = (__pyx_v_j - 1);
      goto __pyx_L24;
    }
    __pyx_L24:;

    /* "/private/tmp/PI/PI/align.pyx":121 */
    __pyx_7 = (__pyx_v_data & (1 << 0));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":122 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":123 */
      __pyx_v_nj = (__pyx_v_j - 1);
      goto __pyx_L25;
    }
    __pyx_L25:;

    /* "/private/tmp/PI/PI/align.pyx":125 */
    __pyx_v_new_len = (__pyx_v_new_len + 1);

    /* "/private/tmp/PI/PI/align.pyx":127 */
    __pyx_v_i = __pyx_v_ni;

    /* "/private/tmp/PI/PI/align.pyx":128 */
    __pyx_v_j = __pyx_v_nj;
  }

  /* "/private/tmp/PI/PI/align.pyx":130 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_5, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_3 = PyInt_FromLong(__pyx_v_new_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_n_i);
  __pyx_3 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_new_seq1);
  __pyx_v_new_seq1 = __pyx_5;
  __pyx_5 = 0;

  /* "/private/tmp/PI/PI/align.pyx":131 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_3, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_new_len); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_n_i);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_v_new_seq2);
  __pyx_v_new_seq2 = __pyx_3;
  __pyx_3 = 0;

  /* "/private/tmp/PI/PI/align.pyx":134 */
  __pyx_v_s1 = __pyx_v_new_len;
  __pyx_v_s2 = __pyx_v_new_len;

  /* "/private/tmp/PI/PI/align.pyx":135 */
  __pyx_v_gaps = 0;

  /* "/private/tmp/PI/PI/align.pyx":137 */
  __pyx_v_i = __pyx_v_i_max;

  /* "/private/tmp/PI/PI/align.pyx":138 */
  __pyx_v_j = __pyx_v_j_max;

  /* "/private/tmp/PI/PI/align.pyx":140 */
  while (1) {
    __pyx_6 = __pyx_v_i;
    if (__pyx_6) {
      __pyx_6 = __pyx_v_j;
    }
    if (!__pyx_6) break;

    /* "/private/tmp/PI/PI/align.pyx":141 */
    __pyx_v_data = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]);

    /* "/private/tmp/PI/PI/align.pyx":143 */
    __pyx_7 = (__pyx_v_data & (1 << 2));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":144 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":145 */
      __pyx_v_nj = __pyx_v_j;

      /* "/private/tmp/PI/PI/align.pyx":146 */
      __pyx_v_dir = (1 << 2);
      goto __pyx_L28;
    }
    __pyx_L28:;

    /* "/private/tmp/PI/PI/align.pyx":148 */
    __pyx_7 = (__pyx_v_data & (1 << 1));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":149 */
      __pyx_v_ni = __pyx_v_i;

      /* "/private/tmp/PI/PI/align.pyx":150 */
      __pyx_v_nj = (__pyx_v_j - 1);

      /* "/private/tmp/PI/PI/align.pyx":151 */
      __pyx_v_dir = (1 << 1);
      goto __pyx_L29;
    }
    __pyx_L29:;

    /* "/private/tmp/PI/PI/align.pyx":153 */
    __pyx_7 = (__pyx_v_data & (1 << 0));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":154 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":155 */
      __pyx_v_nj = (__pyx_v_j - 1);

      /* "/private/tmp/PI/PI/align.pyx":156 */
      __pyx_v_dir = (1 << 0);
      goto __pyx_L30;
    }
    __pyx_L30:;

    /* "/private/tmp/PI/PI/align.pyx":158 */
    __pyx_6 = (__pyx_v_dir == (1 << 0));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":159 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":160 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":161 */
      __pyx_4 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
      __pyx_1 = PyObject_GetItem(__pyx_v_seq1, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_5 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_5, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/private/tmp/PI/PI/align.pyx":162 */
      __pyx_3 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_seq2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_1 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_1, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      goto __pyx_L31;
    }
    __pyx_L31:;

    /* "/private/tmp/PI/PI/align.pyx":164 */
    __pyx_6 = (__pyx_v_dir == (1 << 1));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":165 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":166 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":168 */
      __pyx_5 = PyObject_GetAttr(__pyx_v_edits1, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
      __pyx_3 = 0;
      __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/private/tmp/PI/PI/align.pyx":169 */
      __pyx_3 = PyInt_FromLong(256); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_5, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/private/tmp/PI/PI/align.pyx":170 */
      __pyx_4 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
      __pyx_1 = PyObject_GetItem(__pyx_v_seq2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_3 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_3, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/private/tmp/PI/PI/align.pyx":171 */
      __pyx_v_gaps = (__pyx_v_gaps + 1);
      goto __pyx_L32;
    }
    __pyx_L32:;

    /* "/private/tmp/PI/PI/align.pyx":173 */
    __pyx_6 = (__pyx_v_dir == (1 << 2));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":174 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":175 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":177 */
      __pyx_5 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_seq1, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_1 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_1, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "/private/tmp/PI/PI/align.pyx":178 */
      __pyx_3 = PyInt_FromLong(256); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_5, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/private/tmp/PI/PI/align.pyx":179 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_edits2, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
      __pyx_1 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;

      /* "/private/tmp/PI/PI/align.pyx":180 */
      __pyx_v_gaps = (__pyx_v_gaps + 1);
      goto __pyx_L33;
    }
    __pyx_L33:;

    /* "/private/tmp/PI/PI/align.pyx":182 */
    __pyx_v_i = __pyx_v_ni;

    /* "/private/tmp/PI/PI/align.pyx":183 */
    __pyx_v_j = __pyx_v_nj;
  }

  /* "/private/tmp/PI/PI/align.pyx":185 */
  __pyx_1 = PyInt_FromLong(__pyx_v_t_max); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_gaps); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
  Py_INCREF(__pyx_v_new_seq1);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_new_seq1);
  Py_INCREF(__pyx_v_new_seq2);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_new_seq2);
  Py_INCREF(__pyx_v_edits1);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_edits1);
  Py_INCREF(__pyx_v_edits2);
  PyTuple_SET_ITEM(__pyx_3, 3, __pyx_v_edits2);
  PyTuple_SET_ITEM(__pyx_3, 4, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 5, __pyx_4);
  __pyx_1 = 0;
  __pyx_4 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("PI.align.NeedlemanWunsch");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_edits1);
  Py_DECREF(__pyx_v_edits2);
  Py_DECREF(__pyx_v_table);
  Py_DECREF(__pyx_v_new_seq1);
  Py_DECREF(__pyx_v_new_seq2);
  Py_DECREF(__pyx_v_seq1);
  Py_DECREF(__pyx_v_seq2);
  Py_DECREF(__pyx_v_S);
  return __pyx_r;
}

static PyObject *__pyx_f_2PI_5align_SmithWaterman(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_2PI_5align_SmithWaterman(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_seq1 = 0;
  PyObject *__pyx_v_seq2 = 0;
  PyObject *__pyx_v_S = 0;
  int __pyx_v_g;
  int __pyx_v_e;
  int __pyx_v_M;
  int __pyx_v_N;
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_v_t_max;
  int __pyx_v_i_max;
  int __pyx_v_j_max;
  int __pyx_v_dir;
  int __pyx_v_v1;
  int __pyx_v_v2;
  int __pyx_v_v3;
  int __pyx_v_m;
  int __pyx_v_new_len;
  int __pyx_v_data;
  int __pyx_v_ni;
  int __pyx_v_nj;
  PyArrayObject *__pyx_v_a;
  int __pyx_v_nrows;
  int __pyx_v_ncols;
  int *__pyx_v_matrix;
  PyObject *__pyx_v_edits1;
  PyObject *__pyx_v_edits2;
  PyObject *__pyx_v_table;
  PyObject *__pyx_v_new_seq1;
  PyObject *__pyx_v_new_seq2;
  int __pyx_v_s1;
  int __pyx_v_s2;
  int __pyx_v_gaps;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  long __pyx_7;
  static char *__pyx_argnames[] = {"seq1","seq2","S","g","e",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOii", __pyx_argnames, &__pyx_v_seq1, &__pyx_v_seq2, &__pyx_v_S, &__pyx_v_g, &__pyx_v_e)) return 0;
  Py_INCREF(__pyx_v_seq1);
  Py_INCREF(__pyx_v_seq2);
  Py_INCREF(__pyx_v_S);
  __pyx_v_a = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_edits1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_edits2 = Py_None; Py_INCREF(Py_None);
  __pyx_v_table = Py_None; Py_INCREF(Py_None);
  __pyx_v_new_seq1 = Py_None; Py_INCREF(Py_None);
  __pyx_v_new_seq2 = Py_None; Py_INCREF(Py_None);

  /* "/private/tmp/PI/PI/align.pyx":196 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_v_edits1);
  __pyx_v_edits1 = __pyx_1;
  __pyx_1 = 0;

  /* "/private/tmp/PI/PI/align.pyx":197 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  Py_DECREF(__pyx_v_edits2);
  __pyx_v_edits2 = __pyx_1;
  __pyx_1 = 0;

  /* "/private/tmp/PI/PI/align.pyx":199 */
  __pyx_2 = PyObject_Length(__pyx_v_seq1); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 199; goto __pyx_L1;}
  __pyx_v_M = (__pyx_2 + 1);

  /* "/private/tmp/PI/PI/align.pyx":200 */
  __pyx_2 = PyObject_Length(__pyx_v_seq2); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  __pyx_v_N = (__pyx_2 + 1);

  /* "/private/tmp/PI/PI/align.pyx":202 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_M); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_N); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_5 = PyList_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyList_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_1 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_5);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_i);
  __pyx_5 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_table);
  __pyx_v_table = __pyx_4;
  __pyx_4 = 0;

  /* "/private/tmp/PI/PI/align.pyx":204 */
  __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_M); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyObject_GetIter(__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  for (;;) {
    __pyx_5 = PyIter_Next(__pyx_3);
    if (!__pyx_5) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
      break;
    }
    __pyx_6 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_i = __pyx_6;
    __pyx_1 = PyInt_FromLong((0 - __pyx_v_i)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    __pyx_5 = PyObject_GetItem(__pyx_v_table, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_5, __pyx_4, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 205; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
  }
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/private/tmp/PI/PI/align.pyx":207 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_N); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = PyObject_GetIter(__pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_5);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
      break;
    }
    __pyx_6 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_i = __pyx_6;
    __pyx_4 = PyInt_FromLong((0 - __pyx_v_i)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_v_table, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyInt_FromLong(__pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_1, __pyx_3, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "/private/tmp/PI/PI/align.pyx":210 */
  if (!__Pyx_TypeTest(__pyx_v_table, __pyx_ptype_2PI_5align_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
  Py_INCREF(__pyx_v_table);
  Py_DECREF(((PyObject *)__pyx_v_a));
  __pyx_v_a = ((PyArrayObject *)__pyx_v_table);

  /* "/private/tmp/PI/PI/align.pyx":212 */
  __pyx_v_nrows = (__pyx_v_a->dimensions[0]);

  /* "/private/tmp/PI/PI/align.pyx":213 */
  __pyx_v_ncols = (__pyx_v_a->dimensions[1]);

  /* "/private/tmp/PI/PI/align.pyx":215 */
  __pyx_v_matrix = ((int *)__pyx_v_a->data);

  /* "/private/tmp/PI/PI/align.pyx":218 */
  for (__pyx_v_i = 1; __pyx_v_i < __pyx_v_M; ++__pyx_v_i) {
    for (__pyx_v_j = 1; __pyx_v_j < __pyx_v_N; ++__pyx_v_j) {
      __pyx_4 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      __pyx_1 = PyObject_GetItem(__pyx_v_seq1, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_3 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      __pyx_5 = PyObject_GetItem(__pyx_v_seq2, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      if (PyObject_Cmp(__pyx_1, __pyx_5, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      __pyx_6 = __pyx_6 == 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      if (__pyx_6) {
        (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = 2;
        goto __pyx_L10;
      }
      /*else*/ {
        (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = (-1);
      }
      __pyx_L10:;
    }
  }

  /* "/private/tmp/PI/PI/align.pyx":226 */
  __pyx_v_i_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":227 */
  __pyx_v_j_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":228 */
  __pyx_v_t_max = 0;

  /* "/private/tmp/PI/PI/align.pyx":230 */
  for (__pyx_v_i = 1; __pyx_v_i < __pyx_v_M; ++__pyx_v_i) {
    for (__pyx_v_j = 1; __pyx_v_j < __pyx_v_N; ++__pyx_v_j) {

      /* "/private/tmp/PI/PI/align.pyx":233 */
      __pyx_v_dir = 0;

      /* "/private/tmp/PI/PI/align.pyx":235 */
      __pyx_v_v1 = (__pyx_v_matrix[(((__pyx_v_i - 1) * __pyx_v_ncols) + (__pyx_v_j - 1))]);

      /* "/private/tmp/PI/PI/align.pyx":236 */
      __pyx_v_v2 = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + (__pyx_v_j - 1))]);

      /* "/private/tmp/PI/PI/align.pyx":237 */
      __pyx_v_v3 = (__pyx_v_matrix[(((__pyx_v_i - 1) * __pyx_v_ncols) + __pyx_v_j)]);

      /* "/private/tmp/PI/PI/align.pyx":239 */
      __pyx_6 = (__pyx_v_v1 > 255);
      if (!__pyx_6) {
        __pyx_4 = PyInt_FromLong((__pyx_v_v1 & 0xffffff00)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 239; goto __pyx_L1;}
        if (PyObject_Cmp(__pyx_4, Py_False, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 239; goto __pyx_L1;}
        __pyx_6 = __pyx_6 == 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
      }
      if (__pyx_6) {
        __pyx_v_v1 = (__pyx_v_v1 >> 8);
        goto __pyx_L15;
      }
      __pyx_L15:;

      /* "/private/tmp/PI/PI/align.pyx":241 */
      __pyx_6 = (__pyx_v_v2 > 255);
      if (!__pyx_6) {
        __pyx_3 = PyInt_FromLong((__pyx_v_v1 & 0xffffff00)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
        if (PyObject_Cmp(__pyx_3, Py_False, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
        __pyx_6 = __pyx_6 == 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
      }
      if (__pyx_6) {
        __pyx_v_v2 = (__pyx_v_v2 >> 8);
        goto __pyx_L16;
      }
      __pyx_L16:;

      /* "/private/tmp/PI/PI/align.pyx":243 */
      __pyx_6 = (__pyx_v_v3 > 255);
      if (!__pyx_6) {
        __pyx_1 = PyInt_FromLong((__pyx_v_v1 & 0xffffff00)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
        if (PyObject_Cmp(__pyx_1, Py_False, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
        __pyx_6 = __pyx_6 == 0;
        Py_DECREF(__pyx_1); __pyx_1 = 0;
      }
      if (__pyx_6) {
        __pyx_v_v3 = (__pyx_v_v3 >> 8);
        goto __pyx_L17;
      }
      __pyx_L17:;

      /* "/private/tmp/PI/PI/align.pyx":246 */
      __pyx_v_v1 = (__pyx_v_v1 + (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]));

      /* "/private/tmp/PI/PI/align.pyx":247 */
      __pyx_v_v2 = (__pyx_v_v2 - 2);

      /* "/private/tmp/PI/PI/align.pyx":248 */
      __pyx_v_v3 = (__pyx_v_v3 - 2);

      /* "/private/tmp/PI/PI/align.pyx":250 */
      __pyx_6 = (__pyx_v_v1 > 0);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v1;
        goto __pyx_L18;
      }
      /*else*/ {
        __pyx_v_m = 0;
      }
      __pyx_L18:;

      /* "/private/tmp/PI/PI/align.pyx":255 */
      __pyx_6 = (__pyx_v_v2 > __pyx_v_m);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v2;
        goto __pyx_L19;
      }
      __pyx_L19:;

      /* "/private/tmp/PI/PI/align.pyx":258 */
      __pyx_6 = (__pyx_v_v3 > __pyx_v_m);
      if (__pyx_6) {
        __pyx_v_m = __pyx_v_v3;
        goto __pyx_L20;
      }
      __pyx_L20:;

      /* "/private/tmp/PI/PI/align.pyx":261 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v1);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 0));
        goto __pyx_L21;
      }
      __pyx_L21:;

      /* "/private/tmp/PI/PI/align.pyx":264 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v2);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 1));
        goto __pyx_L22;
      }
      __pyx_L22:;

      /* "/private/tmp/PI/PI/align.pyx":267 */
      __pyx_6 = (__pyx_v_m == __pyx_v_v3);
      if (__pyx_6) {
        __pyx_v_dir = (__pyx_v_dir | (1 << 2));
        goto __pyx_L23;
      }
      __pyx_L23:;

      /* "/private/tmp/PI/PI/align.pyx":270 */
      __pyx_6 = (__pyx_v_m >= __pyx_v_t_max);
      if (__pyx_6) {

        /* "/private/tmp/PI/PI/align.pyx":271 */
        __pyx_v_t_max = __pyx_v_m;

        /* "/private/tmp/PI/PI/align.pyx":272 */
        __pyx_v_i_max = __pyx_v_i;

        /* "/private/tmp/PI/PI/align.pyx":273 */
        __pyx_v_j_max = __pyx_v_j;
        goto __pyx_L24;
      }
      __pyx_L24:;

      /* "/private/tmp/PI/PI/align.pyx":275 */
      __pyx_v_m = (__pyx_v_m << 8);

      /* "/private/tmp/PI/PI/align.pyx":276 */
      __pyx_v_m = (__pyx_v_m | __pyx_v_dir);

      /* "/private/tmp/PI/PI/align.pyx":278 */
      (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) = __pyx_v_m;
    }
  }

  /* "/private/tmp/PI/PI/align.pyx":281 */
  __pyx_v_i = __pyx_v_i_max;

  /* "/private/tmp/PI/PI/align.pyx":282 */
  __pyx_v_j = __pyx_v_j_max;

  /* "/private/tmp/PI/PI/align.pyx":284 */
  __pyx_v_new_len = 0;

  /* "/private/tmp/PI/PI/align.pyx":286 */
  while (1) {
    __pyx_6 = ((__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) > 0);
    if (!__pyx_6) break;

    /* "/private/tmp/PI/PI/align.pyx":287 */
    __pyx_v_data = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]);

    /* "/private/tmp/PI/PI/align.pyx":289 */
    __pyx_7 = (__pyx_v_data & (1 << 2));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":290 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":291 */
      __pyx_v_nj = __pyx_v_j;
      goto __pyx_L27;
    }
    __pyx_L27:;

    /* "/private/tmp/PI/PI/align.pyx":293 */
    __pyx_7 = (__pyx_v_data & (1 << 1));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":294 */
      __pyx_v_ni = __pyx_v_i;

      /* "/private/tmp/PI/PI/align.pyx":295 */
      __pyx_v_nj = (__pyx_v_j - 1);
      goto __pyx_L28;
    }
    __pyx_L28:;

    /* "/private/tmp/PI/PI/align.pyx":297 */
    __pyx_7 = (__pyx_v_data & (1 << 0));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":298 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":299 */
      __pyx_v_nj = (__pyx_v_j - 1);
      goto __pyx_L29;
    }
    __pyx_L29:;

    /* "/private/tmp/PI/PI/align.pyx":301 */
    __pyx_v_new_len = (__pyx_v_new_len + 1);

    /* "/private/tmp/PI/PI/align.pyx":303 */
    __pyx_v_i = __pyx_v_ni;

    /* "/private/tmp/PI/PI/align.pyx":304 */
    __pyx_v_j = __pyx_v_nj;
  }

  /* "/private/tmp/PI/PI/align.pyx":306 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_5, __pyx_n_zeros); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_3 = PyInt_FromLong(__pyx_v_new_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_i);
  __pyx_3 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_new_seq1);
  __pyx_v_new_seq1 = __pyx_5;
  __pyx_5 = 0;

  /* "/private/tmp/PI/PI/align.pyx":307 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_zeros); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_new_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_n_i);
  __pyx_1 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_v_new_seq2);
  __pyx_v_new_seq2 = __pyx_3;
  __pyx_3 = 0;

  /* "/private/tmp/PI/PI/align.pyx":310 */
  __pyx_v_s1 = __pyx_v_new_len;
  __pyx_v_s2 = __pyx_v_new_len;

  /* "/private/tmp/PI/PI/align.pyx":311 */
  __pyx_v_gaps = 0;

  /* "/private/tmp/PI/PI/align.pyx":313 */
  __pyx_v_i = __pyx_v_i_max;

  /* "/private/tmp/PI/PI/align.pyx":314 */
  __pyx_v_j = __pyx_v_j_max;

  /* "/private/tmp/PI/PI/align.pyx":316 */
  while (1) {
    __pyx_6 = ((__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]) > 0);
    if (!__pyx_6) break;

    /* "/private/tmp/PI/PI/align.pyx":317 */
    __pyx_v_data = (__pyx_v_matrix[((__pyx_v_i * __pyx_v_ncols) + __pyx_v_j)]);

    /* "/private/tmp/PI/PI/align.pyx":319 */
    __pyx_7 = (__pyx_v_data & (1 << 2));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":320 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":321 */
      __pyx_v_nj = __pyx_v_j;

      /* "/private/tmp/PI/PI/align.pyx":322 */
      __pyx_v_dir = (1 << 2);
      goto __pyx_L32;
    }
    __pyx_L32:;

    /* "/private/tmp/PI/PI/align.pyx":324 */
    __pyx_7 = (__pyx_v_data & (1 << 1));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":325 */
      __pyx_v_ni = __pyx_v_i;

      /* "/private/tmp/PI/PI/align.pyx":326 */
      __pyx_v_nj = (__pyx_v_j - 1);

      /* "/private/tmp/PI/PI/align.pyx":327 */
      __pyx_v_dir = (1 << 1);
      goto __pyx_L33;
    }
    __pyx_L33:;

    /* "/private/tmp/PI/PI/align.pyx":329 */
    __pyx_7 = (__pyx_v_data & (1 << 0));
    if (__pyx_7) {

      /* "/private/tmp/PI/PI/align.pyx":330 */
      __pyx_v_ni = (__pyx_v_i - 1);

      /* "/private/tmp/PI/PI/align.pyx":331 */
      __pyx_v_nj = (__pyx_v_j - 1);

      /* "/private/tmp/PI/PI/align.pyx":332 */
      __pyx_v_dir = (1 << 0);
      goto __pyx_L34;
    }
    __pyx_L34:;

    /* "/private/tmp/PI/PI/align.pyx":334 */
    __pyx_6 = (__pyx_v_dir == (1 << 0));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":335 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":336 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":337 */
      __pyx_1 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_seq1, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_5 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_5, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 337; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "/private/tmp/PI/PI/align.pyx":338 */
      __pyx_3 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 338; goto __pyx_L1;}
      __pyx_1 = PyObject_GetItem(__pyx_v_seq2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 338; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_4 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 338; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_4, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 338; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L35;
    }
    __pyx_L35:;

    /* "/private/tmp/PI/PI/align.pyx":340 */
    __pyx_6 = (__pyx_v_dir == (1 << 1));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":341 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":342 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":344 */
      __pyx_5 = PyObject_GetAttr(__pyx_v_edits1, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
      __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
      __pyx_3 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 344; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "/private/tmp/PI/PI/align.pyx":345 */
      __pyx_3 = PyInt_FromLong(256); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 345; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 345; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_5, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 345; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/private/tmp/PI/PI/align.pyx":346 */
      __pyx_1 = PyInt_FromLong((__pyx_v_j - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 346; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_seq2, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 346; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_3 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 346; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_3, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 346; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;

      /* "/private/tmp/PI/PI/align.pyx":347 */
      __pyx_v_gaps = (__pyx_v_gaps + 1);
      goto __pyx_L36;
    }
    __pyx_L36:;

    /* "/private/tmp/PI/PI/align.pyx":349 */
    __pyx_6 = (__pyx_v_dir == (1 << 2));
    if (__pyx_6) {

      /* "/private/tmp/PI/PI/align.pyx":350 */
      __pyx_v_s1 = (__pyx_v_s1 - 1);

      /* "/private/tmp/PI/PI/align.pyx":351 */
      __pyx_v_s2 = (__pyx_v_s2 - 1);

      /* "/private/tmp/PI/PI/align.pyx":353 */
      __pyx_5 = PyInt_FromLong((__pyx_v_i - 1)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 353; goto __pyx_L1;}
      __pyx_1 = PyObject_GetItem(__pyx_v_seq1, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 353; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_4 = PyInt_FromLong(__pyx_v_s1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 353; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq1, __pyx_4, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 353; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;

      /* "/private/tmp/PI/PI/align.pyx":354 */
      __pyx_3 = PyInt_FromLong(256); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
      __pyx_5 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_new_seq2, __pyx_5, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 354; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/private/tmp/PI/PI/align.pyx":355 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_edits2, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 355; goto __pyx_L1;}
      __pyx_4 = PyInt_FromLong(__pyx_v_s2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 355; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 355; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
      __pyx_4 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 355; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;

      /* "/private/tmp/PI/PI/align.pyx":356 */
      __pyx_v_gaps = (__pyx_v_gaps + 1);
      goto __pyx_L37;
    }
    __pyx_L37:;

    /* "/private/tmp/PI/PI/align.pyx":358 */
    __pyx_v_i = __pyx_v_ni;

    /* "/private/tmp/PI/PI/align.pyx":359 */
    __pyx_v_j = __pyx_v_nj;
  }

  /* "/private/tmp/PI/PI/align.pyx":361 */
  __pyx_4 = PyInt_FromLong(__pyx_v_t_max); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 361; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(__pyx_v_gaps); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 361; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 361; goto __pyx_L1;}
  Py_INCREF(__pyx_v_new_seq1);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_new_seq1);
  Py_INCREF(__pyx_v_new_seq2);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_new_seq2);
  Py_INCREF(__pyx_v_edits1);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_edits1);
  Py_INCREF(__pyx_v_edits2);
  PyTuple_SET_ITEM(__pyx_3, 3, __pyx_v_edits2);
  PyTuple_SET_ITEM(__pyx_3, 4, __pyx_4);
  PyTuple_SET_ITEM(__pyx_3, 5, __pyx_1);
  __pyx_4 = 0;
  __pyx_1 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("PI.align.SmithWaterman");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_edits1);
  Py_DECREF(__pyx_v_edits2);
  Py_DECREF(__pyx_v_table);
  Py_DECREF(__pyx_v_new_seq1);
  Py_DECREF(__pyx_v_new_seq2);
  Py_DECREF(__pyx_v_seq1);
  Py_DECREF(__pyx_v_seq2);
  Py_DECREF(__pyx_v_S);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"NeedlemanWunsch", (PyCFunction)__pyx_f_2PI_5align_NeedlemanWunsch, METH_VARARGS|METH_KEYWORDS, 0},
  {"SmithWaterman", (PyCFunction)__pyx_f_2PI_5align_SmithWaterman, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initalign(void); /*proto*/
PyMODINIT_FUNC initalign(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("align", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_ptype_2PI_5align_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (!__pyx_ptype_2PI_5align_ndarray) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}

  /* "/private/tmp/PI/PI/align.pyx":15 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/private/tmp/PI/PI/align.pyx":187 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("PI.align");
}

static char *__pyx_filenames[] = {
  "align.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    
    py_name = PyString_FromString(name);
    if (!py_name)
        goto bad;
    return PyImport_Import(py_name);
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
